version: "3.1"
services:
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - ./client:/app
